import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='w-full fex justify-center '>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className=" mt-8 w-full h-80 bg-gray-00">
        <h1 className="text-2xl font-bold text-gray-500">
          Shorts
        </h1>
        <div className="w-full flex space-x-3 p-2">
            {[1,2,3,4,5].map((each)=>(
              <div className="w-40 h-64  rounded-md bg-gray-200">

              </div>
  ))}
        </div>
      </section>
      <section className=" mt-8 w-full h-80 bg-gray-00">
        <div className=" my-2">
        <button className="text-xl inline p-2 font-bold rounded-md bg-gray-600 text-gray-100 ">
          All
        </button>
        </div>
        <div className="w-full  grid grid-cols-2 p-2 gap-4">
            {[1,2,3,4,5,6].map((each)=>(
              <div className="w-84    rounded-md ">
                  <div className="w-full h-32 bg-gray-00 bg-gray-200"></div>
                <div className="w-full">
                  <div className="flex items-center space-x-3  p-2">
                    <div className="w-10 h-10 bg-gray-400 rounded-full "></div>
                    <h1 className="text-md  text-gray-600 font-bold">
                      Video Title
                    </h1>
                  </div>
                  <div className="w-full h-18 ml-20">
                    <h1 className="text-sm font-semibold text-gray-700">
                    Channel Name
                    </h1>
                    <h1 className="text-sm font-semibold text-gray-600">
                     14k vues 6 months 
                    </h1>
                  </div>
                </div>
              </div>
  ))}
        </div>
      </section>  
      
          
    </div>
  )
}
